import { Role } from './role.constant';

export const PERMISSIONS = {
  ADD_CATEGORY: [Role.MANAGER, Role.ADMIN],
  EDIT_CATEGORY: [Role.MANAGER, Role.ADMIN],
  REMOVE_CATEGORY: [Role.ADMIN],
  GET_CATEGORY: [],

  ADD_PUBLISHER: [Role.MANAGER, Role.ADMIN],
  EDIT_PUBLISHER: [Role.MANAGER, Role.ADMIN],
  REMOVE_PUBLISHER: [Role.ADMIN],
  GET_PUBLISHER: [],

  ADD_DESIGNER: [Role.MANAGER, Role.ADMIN],
  EDIT_DESIGNER: [Role.MANAGER, Role.ADMIN],
  REMOVE_DESIGNER: [Role.ADMIN],
  GET_DESIGNER: [],

  ADD_ARTIST: [Role.MANAGER, Role.ADMIN],
  EDIT_ARTIST: [Role.MANAGER, Role.ADMIN],
  REMOVE_ARTIST: [Role.ADMIN],
  GET_ARTIST: [],

  ADD_MECHANISM: [Role.MANAGER, Role.ADMIN],
  EDIT_MECHANISM: [Role.MANAGER, Role.ADMIN],
  REMOVE_MECHANISM: [Role.ADMIN],
  GET_MECHANISM: [],
};
